---
title: "BatchEffectCorrection"
author: "Aram Papazian"
date: "2024-09-06"
output: html_document
---
```{r,warning=FALSE,message=FALSE,echo=FALSE}
library(tidyverse)
library(standR)
library(readxl)
library(SpatialExperiment)
library(umap)
library(ggplot2)
library(dplyr)
library(edgeR)
library(limma)
library(ggrepel)
library(DT)
library(msigdb)
library(GSEABase)
library(vissE)
library(igraph)
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
exp_data<-read_excel(choose.files())
meta_data<-read_excel(choose.files())

## keep only expression columns
## change column names to match with samples
exp2=exp_data[,-which(grepl("group",colnames(exp_data)))]
colnames(exp2)[1]="TargetName"
meta_data$Sample_ID=colnames(exp2)[2:ncol(exp2)]
colnames(meta_data)[1]="SegmentDisplayName"
colnames(meta_data)[11:12]=c("ROICoordinateX", "ROICoordinateY")
meta_data<-as.data.frame(meta_data)
## change column strings in meta_data for labeling reasons
## Slide.Name
meta_data<-meta_data %>%mutate(Slide.Name = sapply(strsplit(Slide.Name, "_"), `[`, 1))
## Roi
meta_data<-meta_data %>%mutate(Roi = sapply(strsplit(Roi, " "), `[`, 1))
exp2<-as.data.frame(exp2)
## remove uvis take till 91 to exclude these samples
meta_data<-meta_data[1:91,]
exp2<-exp2[,1:92]
spe<-readGeoMx(exp2,meta_data)
```

## Dimentionality Reduction
```{r,warning=FALSE,message=FALSE}
spe <- scater::runPCA(spe)
pca_results <- reducedDim(spe, "PCA")
drawPCA(spe, precomputed = pca_results, col = Roi)
drawPCA(spe, precomputed = pca_results, col = Slide.Name)
```
#### Try UMAP
```{r}
spe <- scater::runUMAP(spe, dimred = "PCA")
plotDR(spe, dimred = "UMAP", col = Roi)
plotDR(spe, dimred = "UMAP", col = Slide.Name)
```

## Normalization
```{r}
spe_tmm <- geomxNorm(spe, method = "TMM")
plotRLExpr(spe_tmm, assay = 2, color = Slide.Name) + ggtitle("TMM")
```
```{r}
spe_tmm <- scater::runPCA(spe_tmm)

pca_results_tmm <- reducedDim(spe_tmm, "PCA")

plotPairPCA(spe_tmm, precomputed = pca_results_tmm, color = Roi)
plotPairPCA(spe_tmm, precomputed = pca_results_tmm, color = Slide.Name)
```

## Batch Correction
### RUV4
```{r,message=FALSE,warning=FALSE,echo=FALSE}
spe <- findNCGs(spe, batch_name = "Slide.Name", top_n = 300)

## run batch effect correction (RUV4) based on multiple k values
for(i in seq(11)){
  spe_ruv <- geomxBatchCorrection(spe, factors = "Roi", 
                   NCGs = metadata(spe)$NCGs, k = i)
  
  print(plotPairPCA(spe_ruv, assay = 2, n_dimension = 4, color = Roi, title = paste0("k = ", i)))
  
}

```

#### Pick k=10
```{r,echo=FALSE}
spe_ruv <- geomxBatchCorrection(spe, factors = "Roi", 
                   NCGs = metadata(spe)$NCGs, k = 5)
spe_ruv <- scater::runPCA(spe_ruv)

pca_results_ruv <- reducedDim(spe_ruv, "PCA")

plotPairPCA(spe_ruv, precomputed = pca_results_ruv, color = Roi, title = "RUV4, k = 5", n_dimension = 4)
plotPairPCA(spe_ruv, precomputed = pca_results_ruv, color = Slide.Name, title = "RUV4, k = 5", n_dimension = 4)
```

## Evaluation
```{r}
spe_list <- list(spe, spe_ruv)

plotClusterEvalStats(spe_list = spe_list,
                     bio_feature_name = "Roi",
                     batch_feature_name = "Slide.Name",
                     data_names = c("Raw","RUV4"))

```

## Differential Expression
```{r}
dge <- SE2DGEList(spe_ruv)
design <- model.matrix(~0 + Roi + ruv_W1 + ruv_W2 + ruv_W3 + ruv_W4+ ruv_W5, data = colData(spe_ruv))

colnames(design) <- gsub("^Roi","",colnames(design))
colnames(design) <- gsub(" ","_",colnames(design))
  
colnames(design)

```
```{r}
contr.matrix <- makeContrasts(
   BvT = MM - Naevus,
   levels = colnames(design))
keep <- filterByExpr(dge, design)
table(keep)
rownames(dge)[!keep]
dge_all <- dge[keep, ]
```

```{r}
dge_all <- estimateDisp(dge_all, design = design, robust = TRUE)
plotBCV(dge_all, legend.position = "topleft", ylim = c(0, 1.3))
bcv_df <- data.frame(
  'BCV' = sqrt(dge_all$tagwise.dispersion),
  'AveLogCPM' = dge_all$AveLogCPM,
  'gene_id' = rownames(dge_all)
)

highbcv <- bcv_df$BCV > 0.8
highbcv_df <- bcv_df[highbcv, ]
points(highbcv_df$AveLogCPM, highbcv_df$BCV, col = "red")
text(highbcv_df$AveLogCPM, highbcv_df$BCV, labels = highbcv_df$gene_id, pos = 4)
```

```{r}
v <- voom(dge_all, design, plot = TRUE) 
```
```{r}
fit <- lmFit(v)

fit_contrast <- contrasts.fit(fit, contrasts = contr.matrix)

efit <- eBayes(fit_contrast, robust = TRUE)

results_efit<- decideTests(efit, p.value = 0.05)
summary_efit <- summary(results_efit)

summary_efit
```
```{r}
de_results_BvT <- topTable(efit, coef = 1, sort.by = "P", n = Inf)

de_genes_toptable_BvT <- topTable(efit, coef = 1, sort.by = "P", n = Inf, p.value = 0.05)

de_results_BvT %>% 
  mutate(DE = ifelse(logFC > 0 & adj.P.Val <0.05, "UP", 
                       ifelse(logFC <0 & adj.P.Val<0.05, "DOWN", "NOT DE"))) %>%
  ggplot(aes(AveExpr, logFC, col = DE)) + 
  geom_point(shape = 1, size = 1) + 
  geom_text_repel(data = de_genes_toptable_BvT %>% 
                    mutate(DE = ifelse(logFC > 0 & adj.P.Val <0.05, "UP", 
                       ifelse(logFC <0 & adj.P.Val<0.05, "DOWN", "NOT DE"))) %>%
                    rownames_to_column(), aes(label = rowname)) +
  theme_bw() +
  xlab("Average log-expression") +
  ylab("Log-fold-change") +
  ggtitle("Melanoma vs. Nevi (limma-voom)") +
  scale_color_manual(values = c("blue","gray","red")) +
  theme(text = element_text(size=15))
```
```{r}
updn_cols <- c(RColorBrewer::brewer.pal(6, 'Greens')[2], RColorBrewer::brewer.pal(6, 'Purples')[2])

de_genes_toptable_BvT %>% 
  dplyr::select(c("logFC", "AveExpr", "P.Value", "adj.P.Val")) %>%
  DT::datatable(caption = 'Melanoma vs. Nevi (limma-voom)') %>%
  DT::formatStyle('logFC',
                valueColumns = 'logFC',
                backgroundColor = DT::styleInterval(0, rev(updn_cols))) %>%
  DT::formatSignif(1:4, digits = 4)

```
```{r}
msigdb_hs <- getMsigdb(version = '7.2')
msigdb_hs <- appendKEGG(msigdb_hs)

sc <- listSubCollections(msigdb_hs)

gsc <- c(subsetCollection(msigdb_hs, c('h')),
  subsetCollection(msigdb_hs, 'c2', sc[grepl("^CP:",sc)]),
  subsetCollection(msigdb_hs, 'c5', sc[grepl("^GO:",sc)])) %>%
  GeneSetCollection()
fry_indices <- ids2indices(lapply(gsc, geneIds), rownames(v), remove.empty = FALSE)
names(fry_indices) <- sapply(gsc, setName)

gsc_category <- sapply(gsc, function(x) bcCategory(collectionType(x)))
gsc_category <- gsc_category[sapply(fry_indices, length) > 5]

gsc_subcategory <- sapply(gsc, function(x) bcSubCategory(collectionType(x)))
gsc_subcategory <- gsc_subcategory[sapply(fry_indices, length) > 5]

fry_indices <- fry_indices[sapply(fry_indices, length) > 5]

names(gsc_category) = names(gsc_subcategory) = names(fry_indices)

fry_indices_cat <- split(fry_indices, gsc_category[names(fry_indices)])
fry_res_out <- lapply(fry_indices_cat, function (x) {
  limma::fry(v, index = x, design = design, contrast = contr.matrix[,1], robust = TRUE)
})

post_fry_format <- function(fry_output, gsc_category, gsc_subcategory){
  names(fry_output) <- NULL
  fry_output <- do.call(rbind, fry_output)
  fry_output$GenesetName <- rownames(fry_output)
  fry_output$GenesetCat <- gsc_category[rownames(fry_output)]
  fry_output$GenesetSubCat <- gsc_subcategory[rownames(fry_output)]
  return(fry_output)
}

fry_res_sig <- post_fry_format(fry_res_out, gsc_category, gsc_subcategory) %>%
  as.data.frame() %>%
  filter(FDR < 0.05) 

```

```{r}
fry_res_sig %>%
  arrange(FDR) %>%
  filter(Direction == "Up") %>%
  .[seq(20),] %>%
  mutate(GenesetName = factor(GenesetName, levels = .$GenesetName)) %>%
  ggplot(aes(GenesetName, -log(FDR))) +
  geom_bar(stat = "identity", fill = "red") +
  theme_bw() +
  coord_flip() +
  ggtitle("Up-regulated")

fry_res_sig %>%
  arrange(FDR) %>%
  filter(Direction == "Down") %>%
  .[seq(20),] %>%
  mutate(GenesetName = factor(GenesetName, levels = .$GenesetName)) %>%
  ggplot(aes(GenesetName, -log(FDR))) +
  geom_bar(stat = "identity", fill = "blue") +
  theme_bw() +
  coord_flip() +
  ggtitle("Down-regulated")

```
```{r}
dovissE <- function(fry_out, de_table, topN = 6, title = "", specific_clusters = NA){
  
  n_row = min(1000, nrow(fry_out))
  gs_sig_name <- fry_out %>% 
    filter(FDR < 0.05) %>%
    arrange(FDR) %>% 
    .[1:n_row,] %>% 
    rownames()
  gsc_sig <- gsc[gs_sig_name,]
  
  gs_ovlap <- computeMsigOverlap(gsc_sig, thresh = 0.15)
  gs_ovnet <- computeMsigNetwork(gs_ovlap, gsc)
  
  gs_stats <- -log10(fry_out[gs_sig_name,]$FDR)
  names(gs_stats) <- gs_sig_name
  
  #identify clusters
  grps = cluster_walktrap(gs_ovnet)
  #extract clustering results
  grps = groups(grps)
  #sort by cluster size
  grps = grps[order(sapply(grps, length), decreasing = TRUE)]
  
  # write output
  output_clusters <- list()
  for(i in seq(length(grps))){
    output_clusters[[i]] <- data.frame(geneset = grps[[i]], cluster = paste0("cluster",names(grps)[i]))
  }
  output_clusters <<- output_clusters %>% bind_rows()
  
  if(is.na(specific_clusters)){
    grps <- grps[1:topN]
  } else {
    grps <- grps[specific_clusters %>% as.character()]
  }
  
  #plot the top 12 clusters
  set.seed(36) #set seed for reproducible layout
  p1 <<- plotMsigNetwork(gs_ovnet, markGroups = grps, 
                        genesetStat = gs_stats, rmUnmarkedGroups = TRUE) +
    scico::scale_fill_scico(name = "-log10(FDR)")
  
  p2 <<- plotMsigWordcloud(gsc, grps, type = 'Name')
  
  genes <- unique(unlist(geneIds(gsc_sig)))
  
  genes_logfc <- de_table %>% rownames_to_column() %>% filter(rowname %in% genes) %>% .$logFC
  names(genes_logfc) <- de_table %>% rownames_to_column() %>% filter(rowname %in% genes) %>% .$rowname
  
  p3 <<- plotGeneStats(genes_logfc, gsc, grps) +
    geom_hline(yintercept = 0, colour = 2, lty = 2) +
    ylab("logFC")
  
  #p4 <- plotMsigPPI(ppi, gsc, grps[1:topN], geneStat = genes_logfc) +
  #  guides(col=guide_legend(title="logFC"))
  
  p<-p2 + p1 + p3 + patchwork::plot_layout(ncol = 3) +
          patchwork::plot_annotation(title = title)
  ggsave("my_plot.png",p,width = 15,height = 10,dpi = 300)
}
```


```{r}
dovissE(fry_res_sig, de_genes_toptable_BvT, topN = 9, title = "Melanoma vs. Nevi" )
```

```{r}
#png("my_plot.png", width = 1000, height = 800,res = 300)  # Width and height are in pixels
dovissE(fry_res_sig, de_genes_toptable_BvT, topN = 9, title = "Melanoma vs. Nevi")
#dev.off()

```

